[package]
name = "actix-svelte"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-files = "0.6.0"
actix-web = "4"
actix-web-actors = "4.1.0"
actix = "0.13.0"
rand = "0.8.5"